import { Router } from 'express';
import type { Response } from 'express';
import { requireAuth, type AuthRequest } from '../middlewares/auth.js';
import { getDashboard } from '../services/dashboard.service.js';
import { listCustomers } from '../services/catalog.service.js';
import * as catalog from '../controllers/catalog.controller.js';
import * as orders from '../controllers/orders.controller.js';
import * as deliveryZones from '../controllers/delivery-zones.controller.js';
import { orderEvents } from '../lib/events.js';
import * as whatsappConnection from '../controllers/whatsapp-connection.controller.js';
import * as whatsappWeb from '../controllers/whatsapp-web.controller.js';
import * as management from '../controllers/management.controller.js';
import * as settings from '../controllers/settings.controller.js';
import { asyncHandler } from '../middlewares/async-handler.js';

export const apiRouter = Router();
apiRouter.use(requireAuth);
apiRouter.get('/dashboard', asyncHandler(async (req: AuthRequest, res: Response) => res.json(await getDashboard(req.auth!.restaurantId))));
apiRouter.get('/catalog', asyncHandler(catalog.index));
apiRouter.post('/catalog/products', asyncHandler(catalog.create));
apiRouter.patch('/catalog/products/:id', asyncHandler(catalog.update));
apiRouter.delete('/catalog/products/:id', asyncHandler(catalog.destroy));
apiRouter.get('/customers', asyncHandler(async (req: AuthRequest, res: Response) => res.json(await listCustomers(req.auth!.restaurantId))));
apiRouter.get('/orders', asyncHandler(orders.index));
apiRouter.post('/orders', asyncHandler(orders.create));
apiRouter.patch('/orders/:id/status', asyncHandler(orders.updateStatus));
apiRouter.get('/delivery-zones', asyncHandler(deliveryZones.index));
apiRouter.post('/delivery-zones', asyncHandler(deliveryZones.create));
apiRouter.patch('/delivery-zones/:id', asyncHandler(deliveryZones.update));
apiRouter.delete('/delivery-zones/:id', asyncHandler(deliveryZones.destroy));
apiRouter.get('/coupons', asyncHandler(management.couponsIndex));
apiRouter.post('/coupons', asyncHandler(management.couponsCreate));
apiRouter.patch('/coupons/:id', asyncHandler(management.couponsUpdate));
apiRouter.delete('/coupons/:id', asyncHandler(management.couponsDestroy));
apiRouter.get('/promotions', asyncHandler(management.promotionsIndex));
apiRouter.post('/promotions', asyncHandler(management.promotionsCreate));
apiRouter.patch('/promotions/:id', asyncHandler(management.promotionsUpdate));
apiRouter.delete('/promotions/:id', asyncHandler(management.promotionsDestroy));
apiRouter.get('/settings', asyncHandler(settings.show));
apiRouter.patch('/settings', asyncHandler(settings.update));
apiRouter.get('/integrations/meta-whatsapp', whatsappConnection.status);
apiRouter.post('/integrations/meta-whatsapp/complete', whatsappConnection.complete);
apiRouter.patch('/integrations/meta-whatsapp/automation', whatsappConnection.automation);
apiRouter.get('/integrations/whatsapp', whatsappWeb.status);
apiRouter.post('/integrations/whatsapp/connect', whatsappWeb.start);
apiRouter.delete('/integrations/whatsapp', whatsappWeb.reset);
apiRouter.post('/integrations/whatsapp/test', whatsappWeb.test);
apiRouter.get('/integrations/whatsapp/events', whatsappWeb.events);
apiRouter.patch('/integrations/whatsapp/automation', whatsappWeb.automation);
apiRouter.get('/integrations/whatsapp-web/status', whatsappWeb.status);
apiRouter.post('/integrations/whatsapp-web/start', whatsappWeb.start);
apiRouter.delete('/integrations/whatsapp-web/session', whatsappWeb.reset);
apiRouter.patch('/integrations/whatsapp-web/automation', whatsappWeb.automation);
apiRouter.get('/events', (req: AuthRequest, res) => {
  res.setHeader('Content-Type', 'text/event-stream'); res.setHeader('Cache-Control', 'no-cache'); res.setHeader('Connection', 'keep-alive');
  const handler = (event: { restaurantId: string }) => { if (event.restaurantId === req.auth!.restaurantId) res.write(`data: ${JSON.stringify(event)}\n\n`); };
  orderEvents.on('changed', handler); res.write('event: connected\ndata: {}\n\n');
  req.on('close', () => orderEvents.off('changed', handler));
});
