import { useEffect, useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, BadgeCheck, Bike, Check, ChevronRight, Clock3, MapPin, Plus, Search, ShoppingBag, ShoppingCart, Sparkles, Store, TicketPercent, Trash2, X } from 'lucide-react';
import { createId } from '../lib/id';
import './PublicMenu.css';

const crypto = { randomUUID: createId };

const API_URL = import.meta.env.VITE_API_URL ?? 'http://localhost:3000/api';
const brl = (value: number) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value);
const pizzaDayPromotion = () => `${['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'][new Date().getDay()]} da Pizza`;
type Product = { id: string; name: string; description?: string; imageUrl?: string | null; basePrice: number; promotionalPrice?: number | null; active: boolean; isPizza: boolean };
type Category = { id: string; name: string; icon?: string | null; products: Product[] };
type Size = { id: string; name: string; slices: number; maxFlavors: number; priceMultiplier: number };
type Flavor = { id: string; name: string; description?: string | null; surcharge: number };
type Addon = { id: string; name: string; price: number };
type Zone = { id: string; neighborhood: string; fee: number; estimatedMinutes: number };
type MenuData = { session: { expiresAt: string; customerName: string | null }; restaurant: { name: string; slug: string; logoUrl?: string | null; bannerUrl?: string | null; primaryColor: string; secondaryColor: string; deliveryEstimateMin: number; deliveryEstimateMax: number; minimumOrder: number; isOpen: boolean }; categories: Category[]; sizes: Size[]; flavors: Flavor[]; crusts: Addon[]; extras: Addon[]; zones: Zone[]; promotions: { id: string; name: string; description?: string | null }[] };
type CartItem = { id: string; productId: string; name: string; imageUrl?: string | null; quantity: number; sizeName?: string | null; flavors?: { names?: string[] }; crust?: { name?: string }; extras?: { names?: string[] }; notes?: string; unitPrice: number; subtotal: number };
type Cart = { id: string | null; items: CartItem[]; subtotal: number; couponCode?: string | null; discount?: number };

async function publicApi<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`${API_URL}/public${path}`, { ...init, headers: { 'Content-Type': 'application/json', ...init?.headers } }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.message ?? 'Não foi possível continuar.'); return body; }
const initials = (name: string) => name.split(/\s+/).map((part) => part[0]).join('').slice(0, 2).toUpperCase();

export function PublicMenu() {
  const { slug, token: routeToken } = useParams(); const navigate = useNavigate();
  const [token, setToken] = useState(routeToken ?? ''); const [menu, setMenu] = useState<MenuData | null>(null); const [cart, setCart] = useState<Cart>({ id: null, items: [], subtotal: 0 }); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [category, setCategory] = useState(''); const [selected, setSelected] = useState<Product | null>(null); const [cartOpen, setCartOpen] = useState(false); const [checkoutOpen, setCheckoutOpen] = useState(false); const [cartNotice, setCartNotice] = useState(0); const [success, setSuccess] = useState<{ number: number; total: number; trackingToken: string } | null>(null);
  useEffect(() => { let cancelled = false; (async () => { setLoading(true); setError(''); try { let activeToken = routeToken; if (!activeToken && slug) { const created = await publicApi<{ token: string }>(`/restaurants/${slug}/sessions`, { method: 'POST', body: '{}' }); activeToken = created.token; if (!cancelled) navigate(`/menu/s/${activeToken}`, { replace: true }); } if (!activeToken) throw new Error('Link de cardápio inválido.'); const [loadedMenu, loadedCart] = await Promise.all([publicApi<MenuData>(`/menu/${activeToken}`), publicApi<Cart>(`/menu/${activeToken}/cart`)]); if (!cancelled) { setToken(activeToken); setMenu(loadedMenu); setCart(loadedCart); setCategory(loadedMenu.categories[0]?.id ?? ''); } } catch (reason) { if (!cancelled) setError(reason instanceof Error && reason.message !== 'Failed to fetch' ? reason.message : 'O cardápio está temporariamente indisponível. Tente novamente em instantes.'); } finally { if (!cancelled) setLoading(false); } })(); return () => { cancelled = true; }; }, [slug, routeToken, navigate]);
  useEffect(() => { if (!cartNotice) return; const timer = window.setTimeout(() => setCartNotice(0), 5_000); return () => window.clearTimeout(timer); }, [cartNotice]);
  useEffect(() => { if (!token) return; const refresh = () => { void publicApi<MenuData>(`/menu/${token}`).then((next) => { setMenu(next); setCategory((current) => next.categories.some((item) => item.id === current) ? current : next.categories[0]?.id ?? ''); }).catch(() => undefined); }; const timer = window.setInterval(refresh, 10_000); return () => window.clearInterval(timer); }, [token]);
  const products = useMemo(() => menu?.categories.flatMap((group) => group.products.map((product) => ({ ...product, categoryId: group.id }))).filter((product) => (!category || product.categoryId === category) && `${product.name} ${product.description ?? ''}`.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'))) ?? [], [menu, category, query]);
  const itemCount = cart.items.reduce((sum, item) => sum + item.quantity, 0);
  async function addItem(product: Product, configuration?: Config) { if (!product.active) return; setCart(await publicApi<Cart>(`/menu/${token}/cart/items`, { method: 'POST', body: JSON.stringify({ productId: product.id, quantity: 1, notes: configuration?.notes, pizza: configuration ? { sizeId: configuration.size.id, flavorIds: configuration.flavors.map((item) => item.id), crustId: configuration.crust.id, extraIds: configuration.extras.map((item) => item.id) } : undefined }) })); setSelected(null); setCartNotice((current) => current + 1); }
  async function removeItem(itemId: string) { setCart(await publicApi<Cart>(`/menu/${token}/cart/items/${itemId}`, { method: 'DELETE' })); }
  if (loading) return <MenuSkeleton />; if (error || !menu) return <div className="public-error"><div>🍕</div><h1>Este link não está disponível</h1><p>{error || 'Abra o cardápio novamente.'}</p><a href="/">Voltar ao início</a></div>;
  if (success) return <OrderSuccess result={success} restaurant={menu.restaurant.name} onTrack={() => navigate(`/pedido/${success.trackingToken}`)} onBack={() => { setSuccess(null); setCheckoutOpen(false); setCartOpen(false); }} />;
  return <div className="menu-shell" style={{ '--brand': menu.restaurant.primaryColor, '--brand-dark': menu.restaurant.secondaryColor } as React.CSSProperties}>
    <header className="menu-header"><div className="restaurant-mark"><span>{initials(menu.restaurant.name)}</span><div><strong>{menu.restaurant.name}</strong><small><i /> Aberto agora</small></div></div><button className="header-order" onClick={() => setCartOpen(true)}><ShoppingBag /><span>{itemCount}</span></button></header>
    <main><section className="menu-welcome"><div><span className="welcome-kicker">{menu.session.customerName ? `Olá, ${menu.session.customerName}! 👋` : 'Bem-vindo! 👋'}</span><h1>O que vamos<br />pedir hoje?</h1></div><div className="delivery-summary"><Clock3 /><span><b>{menu.restaurant.deliveryEstimateMin}–{menu.restaurant.deliveryEstimateMax} min</b><small>Tempo de entrega</small></span></div></section>
      <label className="menu-search"><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar no cardápio..." /><kbd>⌘ K</kbd></label>
      <section className="offer-banner"><img src={menu.restaurant.bannerUrl || '/menu-pizza-optimized.jpg'} alt="Pizza artesanal em promoção" /><div className="offer-overlay"><span><Sparkles /> Oferta de hoje</span><h2>{pizzaDayPromotion()}</h2><p>{menu.promotions[0]?.description ?? 'Sabores selecionados com preço especial.'}</p><button onClick={() => document.getElementById('produtos')?.scrollIntoView({ behavior: 'smooth' })}>Ver oferta <ChevronRight /></button></div></section>
      <nav className="category-rail">{menu.categories.map((item) => <button key={item.id} className={category === item.id ? 'active' : ''} onClick={() => setCategory(item.id)}><span>{item.icon || '•'}</span>{item.name}</button>)}</nav>
      <section className="menu-products" id="produtos"><div className="section-heading"><div><span>Feito com carinho</span><h2>{menu.categories.find((item) => item.id === category)?.name ?? 'Cardápio'}</h2></div><small>{products.length} {products.length === 1 ? 'item' : 'itens'}</small></div>{products.length ? <div className="public-product-grid">{products.map((product) => <ProductCard key={product.id} product={product} onSelect={() => setSelected(product)} />)}</div> : <div className="menu-empty"><span>🍽️</span><b>Nenhum produto por aqui</b><p>Tente outra categoria ou uma nova busca.</p></div>}</section></main>
    {cartNotice > 0 && <aside className="cart-notice" role="status"><Check /><span><strong>Item adicionado ao carrinho!</strong><small>Finalize seu pedido para enviá-lo à pizzaria.</small></span><button onClick={() => { setCartNotice(0); setCartOpen(true); }}>Finalizar pedido <ChevronRight /></button></aside>}
    {itemCount > 0 && <button className="floating-cart" onClick={() => { setCartNotice(0); setCartOpen(true); }}><span><ShoppingCart /><i>{itemCount}</i> Ver carrinho</span><b>{brl(cart.subtotal)}</b></button>}
    <nav className="mobile-menu-nav"><button className="active"><Store />Início</button><button onClick={() => document.querySelector<HTMLInputElement>('.menu-search input')?.focus()}><Search />Buscar</button><button onClick={() => setCartOpen(true)}><span><ShoppingBag />{itemCount > 0 && <i>{itemCount}</i>}</span>Carrinho</button></nav>
    {selected && <ProductCustomizer product={selected} menu={menu} onClose={() => setSelected(null)} onAdd={addItem} />}
    {cartOpen && <CartDrawer cart={cart} zones={menu.zones} onClose={() => setCartOpen(false)} onRemove={removeItem} onCheckout={() => { setCartOpen(false); setCheckoutOpen(true); }} token={token} setCart={setCart} />}
    {checkoutOpen && <Checkout menu={menu} cart={cart} token={token} onClose={() => setCheckoutOpen(false)} onSuccess={(result) => { setSuccess(result); setCart({ id: null, items: [], subtotal: 0 }); }} />}
  </div>;
}

function ProductCard({ product, onSelect }: { product: Product; onSelect: () => void }) { return <article className={`public-product-card ${!product.active ? 'sold-out' : ''}`} onClick={onSelect}><div className="product-photo">{product.isPizza ? <img src={product.imageUrl || '/menu-pizza-optimized.jpg'} alt={product.name} loading="lazy" /> : <div className="drink-visual">🥤</div>}{product.promotionalPrice && <span>-{Math.round((1 - product.promotionalPrice / product.basePrice) * 100)}%</span>}{!product.active && <b>ESGOTADO</b>}</div><div className="public-product-copy"><h3>{product.name}</h3><p>{product.description}</p><div><span>{product.promotionalPrice ? <><del>{brl(product.basePrice)}</del><strong>{brl(product.promotionalPrice)}</strong></> : <><small>A partir de</small><strong>{brl(product.basePrice)}</strong></>}</span><button disabled={!product.active}><Plus /></button></div></div></article>; }

type Config = { size: Size; flavors: Flavor[]; crust: Addon; extras: Addon[]; notes: string; price: number };
function ProductCustomizer({ product, menu, onClose, onAdd }: { product: Product; menu: MenuData; onClose: () => void; onAdd: (product: Product, config?: Config) => Promise<void> }) {
  const [size, setSize] = useState(menu.sizes.find((item) => item.name === 'Grande') ?? menu.sizes[0]); const ownFlavor = menu.flavors.find((item) => item.name.toLocaleLowerCase('pt-BR').includes(product.name.toLocaleLowerCase('pt-BR').split(' ')[0])) ?? menu.flavors[0]; const [flavorCount, setFlavorCount] = useState(1); const [flavors, setFlavors] = useState<Flavor[]>(ownFlavor ? [ownFlavor] : []); const [crust, setCrust] = useState(menu.crusts[0]); const [extras, setExtras] = useState<Addon[]>([]); const [notes, setNotes] = useState('');
  useEffect(() => { if (flavorCount === 1) setFlavors((current) => current.slice(0, 1)); }, [flavorCount]);
  const [adding, setAdding] = useState(false); const [addError, setAddError] = useState('');
  const flavorProducts = menu.categories.flatMap((group) => group.products).filter((item) => item.isPizza); const flavorBase = Math.max(product.promotionalPrice ?? product.basePrice, ...flavors.map((flavor) => flavorProducts.find((item) => item.name === flavor.name)?.basePrice ?? product.basePrice)); const price = product.isPizza ? flavorBase * (size?.priceMultiplier ?? 1) + (crust?.price ?? 0) + extras.reduce((sum, item) => sum + item.price, 0) : product.promotionalPrice ?? product.basePrice; const valid = !product.isPizza || Boolean(size && crust && flavors.length === flavorCount);
  async function addToCart() { setAdding(true); setAddError(''); try { await onAdd(product, product.isPizza ? { size, flavors, crust, extras, notes, price } : undefined); } catch (reason) { setAddError(reason instanceof Error ? reason.message : 'Não foi possível adicionar ao carrinho.'); } finally { setAdding(false); } }
  return <div className="sheet-layer"><button className="sheet-backdrop" onClick={onClose} /><section className="product-sheet"><button className="sheet-close" onClick={onClose}><X /></button><div className="sheet-hero"><img src={product.isPizza ? product.imageUrl || '/menu-pizza-optimized.jpg' : '/menu-pizza-optimized.jpg'} alt={product.name} /><span>Mais pedido</span></div><div className="sheet-content"><span className="sheet-kicker">{menu.restaurant.name} recomenda</span><h2>{product.name}</h2><p className="sheet-description">{product.description}</p>
    {!product.isPizza ? <div className="simple-product-note"><BadgeCheck /> Produto pronto para adicionar ao seu pedido.</div> : <><OptionHeader title="Escolha o tamanho" required detail="Escolha 1" /><div className="size-options">{menu.sizes.map((item) => <button key={item.id} className={size?.id === item.id ? 'selected' : ''} onClick={() => { setSize(item); if (flavorCount > item.maxFlavors) setFlavorCount(1); }}><span><b>{item.name}</b><small>{item.slices} pedaços • até {item.maxFlavors} sabor(es)</small></span><strong>{brl(product.basePrice * item.priceMultiplier)}</strong><i>{size?.id === item.id && <Check />}</i></button>)}</div><OptionHeader title="Quantos sabores?" required detail={`Até ${size?.maxFlavors ?? 1}`} /><div className="choice-pills">{[1, 2, 3].filter((count) => count <= (size?.maxFlavors ?? 1)).map((count) => <button className={flavorCount === count ? 'selected' : ''} key={count} onClick={() => setFlavorCount(count)}>{count} {count > 1 ? 'sabores' : 'sabor'}</button>)}</div>
      {flavorCount > 1 && <><OptionHeader title="Monte sua pizza" required detail={`${flavors.length}/${flavorCount}`} /><div className="flavor-list">{menu.flavors.map((item) => { const checked = flavors.some((flavor) => flavor.id === item.id); return <button key={item.id} className={checked ? 'selected' : ''} onClick={() => setFlavors((current) => checked ? current.filter((flavor) => flavor.id !== item.id) : current.length < flavorCount ? [...current, item] : current)}><span className="mini-pizza"><img src="/menu-pizza-optimized.jpg" alt="" /></span><span><b>{item.name}</b><small>{item.surcharge ? `+ ${brl(item.surcharge)}` : 'Sem acréscimo'}</small></span><i>{checked && <Check />}</i></button>; })}</div>{flavors.length === flavorCount && <div className="pizza-preview"><span>🍕</span><div><small>Sua pizza</small><b>{flavors.map((item) => `½ ${item.name}`).join('  •  ')}</b></div></div>}</>}
      <OptionHeader title="Escolha sua borda" required detail="Escolha 1" /><div className="addon-list">{menu.crusts.map((item) => <button key={item.id} className={crust?.id === item.id ? 'selected' : ''} onClick={() => setCrust(item)}><i>{crust?.id === item.id && <Check />}</i><span><b>{item.name}</b><small>{item.price ? `+ ${brl(item.price)}` : 'Grátis'}</small></span></button>)}</div><OptionHeader title="Turbine sua pizza 😋" detail="Opcional" /><div className="addon-list extras">{menu.extras.map((item) => { const checked = extras.some((extra) => extra.id === item.id); return <button key={item.id} className={checked ? 'selected' : ''} onClick={() => setExtras((current) => checked ? current.filter((extra) => extra.id !== item.id) : [...current, item])}><i>{checked && <Check />}</i><span><b>{item.name}</b><small>+ {brl(item.price)}</small></span></button>; })}</div><label className="notes-field"><span>Alguma observação? <small>Opcional</small></span><textarea maxLength={180} value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Ex.: sem cebola, massa bem assada..." /><i>{notes.length}/180</i></label></>}
    </div><footer className="sheet-footer">{addError && <p className="sheet-add-error">{addError}</p>}<button disabled={!valid || adding} onClick={() => void addToCart()}><span>{adding ? 'Adicionando…' : 'Adicionar ao carrinho'}</span><b>{brl(price)}</b></button></footer></section></div>;
}
function OptionHeader({ title, required, detail }: { title: string; required?: boolean; detail: string }) { return <div className="option-heading"><div><h3>{title}</h3>{required && <span>Obrigatório</span>}</div><small>{detail}</small></div>; }

function CartDrawer({ cart, zones, onClose, onRemove, onCheckout, token, setCart }: { cart: Cart; zones: Zone[]; onClose: () => void; onRemove: (id: string) => void; onCheckout: () => void; token: string; setCart: (cart: Cart) => void }) {
  const [removing, setRemoving] = useState<CartItem | null>(null); const [coupon, setCoupon] = useState(''); const [couponMessage, setCouponMessage] = useState(''); const [discount, setDiscount] = useState(cart.discount ?? 0); const estimatedFee = zones[0]?.fee ?? 0;
  async function applyCoupon() { try { const result = await publicApi<{ code: string; discount: number }>(`/menu/${token}/coupon`, { method: 'POST', body: JSON.stringify({ code: coupon }) }); setDiscount(result.discount); setCouponMessage(`Cupom ${result.code} aplicado`); setCart({ ...cart, couponCode: result.code, discount: result.discount }); } catch (reason) { setCouponMessage(reason instanceof Error ? reason.message : 'Cupom inválido.'); } }
  return <div className="sheet-layer"><button className="sheet-backdrop" onClick={onClose} /><aside className="cart-drawer"><header><div><span>Seu pedido</span><h2>Carrinho <small>{cart.items.length}</small></h2></div><button onClick={onClose}><X /></button></header><div className="cart-body">{cart.items.length ? <>{cart.items.map((item) => <article className="cart-line" key={item.id}><div className="cart-thumb">{item.productId.includes('coca') || item.productId.includes('guarana') ? '🥤' : <img src={item.imageUrl || '/menu-pizza-optimized.jpg'} alt="" />}</div><div><h3>{item.quantity}× {item.name}</h3>{item.flavors?.names && <p>{item.flavors.names.map((name) => `½ ${name}`).join(' • ')}</p>}{item.crust?.name && <small>Borda: {item.crust.name}</small>}{item.extras?.names?.length ? <small>Extras: {item.extras.names.join(', ')}</small> : null}<div><strong>{brl(item.subtotal)}</strong><button onClick={() => setRemoving(item)}><Trash2 /> Remover</button></div></div></article>)}<div className="coupon-box"><TicketPercent /><div><b>Possui um cupom?</b><span><input value={coupon} onChange={(event) => setCoupon(event.target.value)} placeholder="Digite o código" /><button onClick={applyCoupon}>Aplicar</button></span>{couponMessage && <small>{couponMessage}</small>}</div></div><div className="cart-totals"><p><span>Subtotal</span><b>{brl(cart.subtotal)}</b></p>{discount > 0 && <p className="discount"><span>Desconto</span><b>− {brl(discount)}</b></p>}<p><span>Entrega <small>calculada no checkout</small></span><b>A partir de {brl(estimatedFee)}</b></p><div><span>Total parcial</span><strong>{brl(cart.subtotal - discount)}</strong></div></div></> : <div className="empty-cart"><ShoppingBag /><h3>Seu carrinho está vazio</h3><p>Escolha algo gostoso no cardápio para começar.</p><button onClick={onClose}>Ver cardápio</button></div>}</div>{cart.items.length > 0 && <footer><button onClick={onCheckout}>Finalizar pedido <ChevronRight /></button><small>🔒 Pagamento seguro e dados protegidos</small></footer>}</aside>{removing && <div className="confirm-remove"><div><h3>Remover este item?</h3><p>{removing.name} será removido do seu pedido.</p><span><button onClick={() => setRemoving(null)}>Cancelar</button><button onClick={() => { onRemove(removing.id); setRemoving(null); }}>Remover</button></span></div></div>}</div>;
}

function Checkout({ menu, cart, token, onClose, onSuccess }: { menu: MenuData; cart: Cart; token: string; onClose: () => void; onSuccess: (result: { number: number; total: number; trackingToken: string }) => void }) {
  const [step, setStep] = useState(0); const [fulfillment, setFulfillment] = useState<'DELIVERY' | 'PICKUP'>('DELIVERY'); const [zoneId, setZoneId] = useState(menu.zones[0]?.id ?? ''); const [form, setForm] = useState({ name: '', phone: '', zipCode: '', street: '', number: '', neighborhood: menu.zones[0]?.neighborhood ?? '', complement: '', city: '', reference: '' }); const [payment, setPayment] = useState<'PIX' | 'CASH' | 'CARD'>('PIX'); const [changeFor, setChangeFor] = useState(''); const [submitting, setSubmitting] = useState(false); const [message, setMessage] = useState(''); const zone = menu.zones.find((item) => item.id === zoneId); const fee = fulfillment === 'DELIVERY' ? zone?.fee ?? 0 : 0; const total = cart.subtotal - (cart.discount ?? 0) + fee;
  function update(name: keyof typeof form, value: string) { setForm((current) => ({ ...current, [name]: value })); }
  function next() { if (step === 1 && (!form.name || form.phone.replace(/\D/g, '').length < 10 || (fulfillment === 'DELIVERY' && (!form.street || !form.number || !zoneId)))) { setMessage('Preencha os campos obrigatórios para continuar.'); return; } setMessage(''); setStep((current) => Math.min(3, current + 1)); }
  async function submit() { setSubmitting(true); setMessage(''); try { const idempotencyKey = crypto.randomUUID(); const result = await publicApi<{ order: { number: number; total: number | string }; trackingToken: string }>(`/menu/${token}/checkout`, { method: 'POST', body: JSON.stringify({ idempotencyKey, fulfillment, customer: { name: form.name, phone: form.phone }, neighborhood: zone?.neighborhood, address: fulfillment === 'DELIVERY' ? form : undefined, paymentMethod: payment, changeFor: changeFor ? Number(changeFor.replace(',', '.')) : undefined }) }); onSuccess({ number: result.order.number, total: Number(result.order.total), trackingToken: result.trackingToken }); } catch (reason) { setMessage(reason instanceof Error ? reason.message : 'Não foi possível criar o pedido.'); } finally { setSubmitting(false); } }
  const labels = ['Entrega', 'Endereço', 'Pagamento', 'Confirmar']; return <div className="checkout-page"><header><button onClick={step ? () => setStep(step - 1) : onClose}><ArrowLeft /></button><div><span>Finalizar pedido</span><b>Checkout seguro</b></div><small>{step + 1}/4</small></header><div className="checkout-progress">{labels.map((label, index) => <span key={label} className={index <= step ? 'active' : ''}><i>{index < step ? <Check /> : index + 1}</i><b>{label}</b></span>)}</div><main>
    {step === 0 && <section className="checkout-card"><span className="checkout-kicker">Como deseja receber?</span><h1>Escolha a melhor opção</h1><div className="fulfillment-grid"><button className={fulfillment === 'DELIVERY' ? 'selected' : ''} onClick={() => setFulfillment('DELIVERY')}><Bike /><span><b>Entrega</b><small>Receba no seu endereço</small></span><i>{fulfillment === 'DELIVERY' && <Check />}</i></button><button className={fulfillment === 'PICKUP' ? 'selected' : ''} onClick={() => setFulfillment('PICKUP')}><Store /><span><b>Retirar no local</b><small>Sem taxa de entrega</small></span><i>{fulfillment === 'PICKUP' && <Check />}</i></button></div>{fulfillment === 'DELIVERY' && <label className="checkout-select">Região de entrega<select value={zoneId} onChange={(event) => { setZoneId(event.target.value); update('neighborhood', menu.zones.find((item) => item.id === event.target.value)?.neighborhood ?? ''); }}>{menu.zones.map((item) => <option key={item.id} value={item.id}>{item.neighborhood} • {brl(item.fee)}</option>)}</select></label>}</section>}
    {step === 1 && <section className="checkout-card"><span className="checkout-kicker">Seus dados</span><h1>{fulfillment === 'DELIVERY' ? 'Onde vamos entregar?' : 'Quem vai retirar?'}</h1><div className="form-grid"><Field label="Nome" value={form.name} setValue={(value) => update('name', value)} placeholder="Como podemos chamar você?" /><Field label="WhatsApp" value={form.phone} setValue={(value) => update('phone', value)} placeholder="(11) 99999-9999" />{fulfillment === 'DELIVERY' && <><Field label="CEP" value={form.zipCode} setValue={(value) => update('zipCode', value)} placeholder="00000-000" /><Field label="Rua" value={form.street} setValue={(value) => update('street', value)} placeholder="Nome da rua" wide /><Field label="Número" value={form.number} setValue={(value) => update('number', value)} placeholder="123" /><Field label="Complemento" value={form.complement} setValue={(value) => update('complement', value)} placeholder="Apto, bloco..." /><Field label="Cidade" value={form.city} setValue={(value) => update('city', value)} placeholder="Sua cidade" /><Field label="Referência" value={form.reference} setValue={(value) => update('reference', value)} placeholder="Próximo a..." /></>}</div></section>}
    {step === 2 && <section className="checkout-card"><span className="checkout-kicker">Pagamento</span><h1>Como prefere pagar?</h1><div className="payment-list">{([{ id: 'PIX', icon: '◇', title: 'PIX', detail: 'Rápido e sem contato' }, { id: 'CASH', icon: 'R$', title: 'Dinheiro', detail: 'Pagamento na entrega' }, { id: 'CARD', icon: '▣', title: 'Cartão na entrega', detail: 'Crédito ou débito' }] as const).map((item) => <button key={item.id} className={payment === item.id ? 'selected' : ''} onClick={() => setPayment(item.id)}><em>{item.icon}</em><span><b>{item.title}</b><small>{item.detail}</small></span><i>{payment === item.id && <Check />}</i></button>)}</div>{payment === 'CASH' && <Field label="Troco para" value={changeFor} setValue={setChangeFor} placeholder="Ex.: 100,00" />}</section>}
    {step === 3 && <section className="checkout-card checkout-review"><span className="checkout-kicker">Tudo certo?</span><h1>Confirme seu pedido</h1><div className="review-store"><span>{initials(menu.restaurant.name)}</span><div><b>{menu.restaurant.name}</b><small>{fulfillment === 'DELIVERY' ? `${zone?.estimatedMinutes ?? 40}–${(zone?.estimatedMinutes ?? 40) + 10} min` : 'Retirada no balcão'}</small></div></div><div className="review-items">{cart.items.map((item) => <p key={item.id}><span>{item.quantity}× {item.name}<small>{item.flavors?.names?.join(' / ')}</small></span><b>{brl(item.subtotal)}</b></p>)}</div><div className="review-detail"><MapPin /><span><small>{fulfillment === 'DELIVERY' ? 'Entregar em' : 'Retirada'}</small><b>{fulfillment === 'DELIVERY' ? `${form.street}, ${form.number} • ${zone?.neighborhood}` : `Balcão do ${menu.restaurant.name}`}</b></span></div><div className="review-detail"><span className="payment-symbol">$</span><span><small>Pagamento</small><b>{payment === 'PIX' ? 'PIX' : payment === 'CASH' ? 'Dinheiro' : 'Cartão na entrega'}</b></span></div><div className="review-total"><p><span>Subtotal</span><b>{brl(cart.subtotal)}</b></p><p><span>Entrega</span><b>{fee ? brl(fee) : 'Grátis'}</b></p><div><span>Total</span><strong>{brl(total)}</strong></div></div></section>}{message && <p className="checkout-error">{message}</p>}</main><footer><div><small>Total</small><strong>{brl(total)}</strong></div><button disabled={submitting} onClick={step === 3 ? submit : next}>{submitting ? 'Enviando...' : step === 3 ? 'Confirmar pedido' : 'Continuar'} <ChevronRight /></button></footer></div>;
}
function Field({ label, value, setValue, placeholder, wide }: { label: string; value: string; setValue: (value: string) => void; placeholder: string; wide?: boolean }) { return <label className={wide ? 'wide' : ''}>{label}<input value={value} onChange={(event) => setValue(event.target.value)} placeholder={placeholder} /></label>; }
function OrderSuccess({ result, restaurant, onTrack, onBack }: { result: { number: number; total: number }; restaurant: string; onTrack: () => void; onBack: () => void }) { return <main className="order-success"><div className="success-confetti">✦ <span>●</span> ✦</div><div className="success-icon"><Check /></div><span>Pedido recebido!</span><h1>Obrigado pelo pedido 💛</h1><p>O {restaurant} já recebeu e vai confirmar em instantes.</p><section><small>Pedido</small><strong>#{result.number}</strong><i /><small>Total</small><b>{brl(result.total)}</b><em>🕐 Aguardando confirmação</em></section><button onClick={onTrack}>Acompanhar pedido <ChevronRight /></button><button className="back-menu" onClick={onBack}>Voltar ao cardápio</button><small>Você receberá atualizações pelo WhatsApp.</small></main>; }
function MenuSkeleton() { return <div className="menu-skeleton"><header><i /><span /></header><main><div className="sk-welcome" /><div className="sk-search" /><div className="sk-banner" /><div className="sk-pills"><i /><i /><i /><i /></div><div className="sk-grid"><i /><i /><i /><i /></div></main></div>; }

export function OrderTracking() {
  const { token = '' } = useParams(); const navigate = useNavigate(); const [order, setOrder] = useState<any>(null); const [error, setError] = useState('');
  useEffect(() => { let live = true; const load = async () => { try { const value = await publicApi(`/orders/${token}`); if (!value) throw new Error(); if (live) setOrder(value); } catch { if (live) setError('Não foi possível localizar este pedido.'); } }; void load(); const timer = window.setInterval(() => void load(), 12_000); return () => { live = false; clearInterval(timer); }; }, [token]);
  if (error) return <div className="public-error"><div>🧾</div><h1>Pedido não encontrado</h1><p>{error}</p></div>; if (!order) return <MenuSkeleton />; const pickup = order.fulfillment === 'PICKUP' || order.address === null; const states = pickup ? ['NEW', 'CONFIRMED', 'PREPARING', 'READY'] : ['NEW', 'CONFIRMED', 'PREPARING', 'READY', 'OUT_FOR_DELIVERY']; const statusIndex = states.indexOf(order.status); const current = order.status === 'DELIVERED' || (pickup && order.status === 'OUT_FOR_DELIVERY') ? states.length - 1 : Math.max(0, statusIndex); const labels: Record<string, string> = { NEW: 'Pedido recebido', CONFIRMED: 'Confirmado', PREPARING: 'Em preparo', READY: pickup ? 'Está pronto para ser retirado' : 'Pronto', OUT_FOR_DELIVERY: 'Saiu para entrega' };
  return <main className="tracking-page"><header><button onClick={() => navigate(-1)}><ArrowLeft /></button><span>Acompanhar pedido</span></header><section className="tracking-hero"><span>Pedido #{order.number}</span><h1>{current < 2 ? 'Seu pedido está com a gente!' : pickup && current === states.length - 1 ? 'Seu pedido está pronto para retirada!' : current < 4 ? 'Estamos preparando tudo 🍕' : 'Já está chegando!'}</h1><p>{order.restaurant?.name ?? 'Restaurante'} • {brl(Number(order.total))}</p></section><section className="tracking-timeline">{states.map((state, index) => <div className={index <= current ? 'done' : ''} key={state}><i>{index <= current ? <Check /> : index + 1}</i><span><b>{labels[state]}</b><small>{index === current ? 'Status atual' : index < current ? 'Concluído' : 'Aguardando'}</small></span></div>)}</section><p className="tracking-update"><span /> Atualização automática a cada 12 segundos</p></main>;
}
